name: Java CI

on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and test with Gradle
      run: ./gradlew clean build
    - name: Assemble a fatJar
      run: ./gradlew jarComplete
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: libs
        path: build/libs
